#!/usr/bin/env bash

if ! docker buildx version >/dev/null 2>/dev/null; then
    echo "ERROR: You need docker buildx on your system to use this script"
    echo "       Refer to https://github.com/docker/buildx#installing"
    exit 1
fi

ROOT_DIR=$(git rev-parse --show-toplevel)
(
    set -x
    docker buildx build --target prod -o artifacts/ "${ROOT_DIR}"
)
